### ISSUE TITLE
Group rolls not working?

### ISSUE THREAD

**Issue by PyroFD3S** [trdischat/grouproll#1] opened 2020-03-26 08:38 UTC
I'm trying to play around with this group rolls module, and when I select a group of PCs it usually only drops one into the group rolls check and it doesn't let me close the window of the group rolls
I get this in the console not sure what it means:
main.js:143 Uncaught (in promise) TypeError: Cannot read property 'halflingLucky' of undefined
    at main.js:143
    at Array.map (<anonymous>)
    at GroupSkillCheck.getTokenList (main.js:134)
    at GroupSkillCheck.getData (main.js:122)
    at GroupSkillCheck._render (foundry.js:3342)
    at GroupSkillCheck.render (foundry.js:3316)
    at Object.onClick (main.js:242)
    at SceneControls._onClickTool (foundry.js:18778)
    at HTMLLIElement.dispatch (jquery.min.js:2)
    at HTMLLIElement.v.handle (jquery.min.js:2)

**Comment by trdischat** [comment] 2020-03-26 15:13
Turns out that the halflingLucky flag does not even exist for Tokens that are not linked to their Actor. I added some code to check for this, and the problem is now fixed.  Please update to the latest version of the module.  Thanks.

**Closed as completed by trdischat** 2020-03-26 15:13 UTC

**Comment by PyroFD3S** [comment] 2020-03-26 15:27
thanks!
